#!/bin/bash

INSTALL_PATH="/usr/local"
FORCE_INSTALL=false

show_help() {
    echo "Usage: ./setup.sh [OPTION]..."
    echo "Install or uninstall WineCharm."
    echo ""
    echo "Options:"
    echo "  -i, --install         Install WineCharm"
    echo "  -u, --uninstall       Uninstall WineCharm"
    echo "  -p, --prefix PATH     Specify installation prefix (default: /usr/local)"
    echo "  -f, --force           Force installation even if dependencies are not met"
    echo "  -h, --help            Display this help and exit"
}

check_dependencies() {
    local missing_programs=()

    if ! command -v "flatpak-spawn" &> /dev/null; then
        local required_programs=(
            'exiftool'
            'wine'
            'winetricks'
            'wrestool'
            'icotool'
            'pgrep'
            'gnome-terminal'
            'xdg-open'
        )

        for prog in "${required_programs[@]}"; do
            if ! command -v "$prog" &> /dev/null; then
                missing_programs+=("$prog")
            fi
        done
    fi

    if [ ${#missing_programs[@]} -ne 0 ]; then
        echo "The following required programs are missing:"
        for prog in "${missing_programs[@]}"; do
            echo "  - $prog"
        done
        echo ""
        echo "Please install them before proceeding or use the -f or --force option to install WineCharm anyway."
        return 1
    fi

    return 0
}

install_files() {
    echo "Installing WineCharm to $INSTALL_PATH..."

    install -Dm755 winecharm.py "$INSTALL_PATH/bin/winecharm"
    install -Dm644 io.github.fastrizwaan.WineCharm.svg "$INSTALL_PATH/share/icons/hicolor/scalable/apps/io.github.fastrizwaan.WineCharm.svg"
    install -Dm755 io.github.fastrizwaan.WineCharm.desktop "$INSTALL_PATH/share/applications/io.github.fastrizwaan.WineCharm.desktop"
    install -Dm644 org.winehq.Wine.png "$INSTALL_PATH/share/icons/hicolor/128x128/apps/org.winehq.Wine.png"

    echo "WineCharm installed successfully."
}

uninstall_files() {
    echo "Uninstalling WineCharm from $INSTALL_PATH..."

    rm -f "$INSTALL_PATH/bin/winecharm"
    rm -f "$INSTALL_PATH/share/icons/hicolor/scalable/apps/io.github.fastrizwaan.WineCharm.svg"
    rm -f "$INSTALL_PATH/share/applications/io.github.fastrizwaan.WineCharm.desktop"
    rm -f "$INSTALL_PATH/share/icons/hicolor/128x128/apps/org.winehq.Wine.png"

    echo "WineCharm uninstalled successfully."
}

# Parse command-line arguments
while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        -i|--install)
        ACTION="install"
        shift
        ;;
        -u|--uninstall)
        ACTION="uninstall"
        shift
        ;;
        -p|--prefix)
        INSTALL_PATH="$2"
        shift
        shift
        ;;
        -f|--force)
        FORCE_INSTALL=true
        shift
        ;;
        -h|--help)
        show_help
        exit 0
        ;;
        *)
        echo "Unknown option: $key"
        show_help
        exit 1
        ;;
    esac
done

if [ -z "$ACTION" ]; then
    show_help
    exit 0
fi

if [ "$ACTION" == "install" ]; then
    if ! check_dependencies && [ "$FORCE_INSTALL" = false ]; then
        echo "Dependencies are not satisfied. Use -f or --force to force the installation."
        exit 1
    fi
    install_files
elif [ "$ACTION" == "uninstall" ]; then
    uninstall_files
fi

